"""Refresh the small Lucide subset used by the workspace, including its license."""
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import re
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://raw.githubusercontent.com/lucide-icons/lucide/main/'
ICONS = {
    'copy': 'copy',
    'zoomIn': 'zoom-in', 'zoomOut': 'zoom-out',
    'plus': 'plus', 'minus': 'minus', 'close': 'x', 'back': 'arrow-left',
    'help': 'circle-question-mark', 'info': 'info', 'expand': 'chevron-down',
    'collapse': 'chevron-up', 'fit': 'maximize', 'search': 'search',
    'download': 'download', 'layers': 'layers', 'settings': 'sliders-horizontal',
    'bell': 'bell', 'people': 'users', 'profile': 'chart-no-axes-combined',
    'ruler': 'ruler', 'area': 'square-dashed', 'undo': 'undo-2', 'trash': 'trash',
    'check': 'check', 'blocked': 'circle-minus', 'uncertain': 'triangle-alert',
    'priority': 'flag',
    'panelOpen': 'panel-left-open', 'panelClose': 'panel-left-close',
    'location': 'locate-fixed',
    'pointer': 'mouse-pointer-2', 'polygon': 'pentagon', 'rectangle': 'rectangle-horizontal',
    'edit': 'square-pen', 'redo': 'redo-2', 'image': 'image',
}

def fetch(item):
    name, icon = item
    source = urlopen(BASE + f'icons/{icon}.svg', timeout=30).read().decode()
    body = re.search(r'<svg[^>]*>(.*?)</svg>', source, re.S).group(1).strip()
    return f"  '{name}': <>{body}</>,"

if __name__ == '__main__':
    with ThreadPoolExecutor(max_workers=5) as pool:
        paths = list(pool.map(fetch, ICONS.items()))
    target = ROOT / 'src/shared/ui/UiIcon.tsx'
    target.write_text(
        "// Lucide icon subset. License: vendor/lucide/LICENSE.\n"
        "// Generated by scripts/vendor_ui_icons.py.\n"
        "const paths = {\n" + '\n'.join(paths) + "\n};\n\n"
        "export type UiIconName = keyof typeof paths;\n"
        "export function UiIcon({ name, size = 18 }: { name: UiIconName; size?: number }): JSX.Element {\n"
        '  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false">{paths[name]}</svg>;\n'
        "}\n", encoding='utf-8')
    license_dir = ROOT / 'vendor/lucide'
    license_dir.mkdir(parents=True, exist_ok=True)
    (license_dir / 'LICENSE').write_bytes(urlopen(BASE + 'LICENSE', timeout=30).read())
    print(f'Updated {len(paths)} icons and license.')
